name: Minify source files

on: [push]

jobs:
  read:
    runs-on: ubuntu-18.04
    
    steps:
    - name: Copy files
      run: cp src/Javascript/syntax.js out
    - name: Copy files
      run: cp src/CSS/syntax.css out
    - name: Checkout
      uses: actions/checkout@v2
    - name: minisauras
      uses: TeamTigers/minisauras@v2.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.MINIFIER }}
      id: dir
      with:
        directory: 'out/'
